### PR TITLE
Added A subscribe Button as mentioned in issue #28

### PR DESCRIPTION
**Pull request by sau-mili**
[#28 ](url)

### CODE REVIEW

**Comment by Its-Aman-Yadav** [comment]
It seems not that great, also it is not working, can you make it work? also remove the conflicts

**Comment by sau-mili** [comment]
It does pop up, when we click, what exactly do you want me to do by "make it work"? can you elaborate?

**Comment by bhaavvya** [comment]
Hello @sau-mili definitely it does pop up on click, can you please add animation on appearance and closing and please see if you can make it responsive.

**Comment by sau-mili** [comment]
I have added animation, but I will revise it

**Comment by sau-mili** [comment]
Can you merge this for now? I keep getting these resolve conflict things..? i will update another pull request with the existing issue or create a new one if you say so?

**Comment by Its-Aman-Yadav** [comment]
Yeah, please make different branch and raise a PR
Thank you @sau-mili

**Pull request closed without merging**
