### PR TITLE
Update licensing.html

### LINKED ISSUE #1392: Feat: Enhance Licensing page
### Describe the feature

Want to enhance Licensing page

### Add ScreenShots

osvlicensing

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Meetjain1**
## Summary

_Briefly describe the purpose of this PR._

## Description

_Explain in detail what this PR is all about. This should include the problem you're solving, the approach taken, and any technical details that reviewers need to know._

This PR updates the styling of the "Licensing" section to enhance readability and align it with the overall theme of the project. Key changes include:

- Improved visual hierarchy with increased font sizes for headings and text.
- Enhanced spacing and alignment for better content organization.
- Updated the background and text colors to ensure consistency with both light and dark modes.
- Applied box-shadow and border-radius to the container for a more polished appearance.

## Images

_Include any relevant images or diagrams that can help reviewers visualize the changes, if applicable_
osvlicensing3
osvlicensing2
osvlicensing

## Issue(s) Addressed

_Enter the issue number of the bug(s) that this PR fixes_

- Template should be strictly **Closes <issue_number>**
- Example: Closes #1392 

## Prerequisites

- [X] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/Its-Aman-Yadav/Community-Site/blob/main/CONTRIBUITING.md)?

### CODE REVIEW

**Comment by Meetjain1** [comment]
@Its-Aman-Yadav sir please review prs since the deadline is 7pm today so I request you to please review as soon as possible.  Thanks

**Comment by Meetjain1** [comment]
@Its-Aman-Yadav @Kalivarapubindusree please review before 7pm

**Comment by Meetjain1** [comment]
@Its-Aman-Yadav

**Comment by Meetjain1** [comment]
@Its-Aman-Yadav

**Review by Its-Aman-Yadav — APPROVED** [review]

**Pull request merged**
