### PR TITLE
contact page enhanced

### PR DESCRIPTION
**Pull request by harikasayani**
I have added icons and changed border color and font color for contact page
Screenshot (138)

Please add GSSOC and Level labels and assign me to this PR.

### CODE REVIEW

**Comment by Its-Aman-Yadav** [comment]
Which issue is this? @harikasayani

**Comment by harikasayani** [comment]
My issue no: #498

**Comment by harikasayani** [comment]
I have resolved my conflicts.
Please merge it.
My issue no: #498

**Comment by Its-Aman-Yadav** [comment]
Thank you

**Review by Its-Aman-Yadav — APPROVED** [review]

**Pull request merged**
