### PR TITLE
added the most requested FAQs

### PR DESCRIPTION
**Pull request by shivathmikavemula**
Hello PA
I have added the most requesting FAQs in the index.html page i.e 6th FAQs.

### Screenshot -
Screenshot (14)

### CODE REVIEW

**Comment by shivathmikavemula** [comment]
I have completed the task so please assign the gssoc levels to it @Its-Aman-Yadav

**Comment by shivathmikavemula** [comment]
their is no FAQ about the feedback #514 @Its-Aman-Yadav 
Its is the Issue number.
#514 
Please provide the gssoc labels to it. @Its-Aman-Yadav

**Comment by Its-Aman-Yadav** [comment]
Done

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by shivathmikavemula** [comment]
Thanks @Its-Aman-Yadav

**Pull request merged**
