### PR TITLE
Fixed border radius and extra padding issue #245

### LINKED ISSUE #245: Feat: Adding Rounding Radius To Get In Touch Send Button
### Describe the feature

The Get In Touch Button will looking more appealing if will make the Send Button Having Some Rounding Radius , so can make it.

### Add ScreenShots

Screenshot (632)

Will Make it to have some rounding radius.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by souvik-maity**
fixes #245 
i have added the required border-radius to the send message button and also removed the extra padding which made the button unnecessarily big.
before:
Screenshot 2024-05-16 230114
After:
large screen:
Screenshot 2024-05-16 231406
medium screen:

Screenshot 2024-05-16 231552
small screen:
Screenshot 2024-05-16 231608

### CODE REVIEW

**Comment by bhaavvya** [comment]
Hello @souvik-maity can you please resolve the issue.

**Comment by souvik-maity** [comment]
> Hello @souvik-maity can you please resolve the conflict.

resolved

**Review by bhaavvya — COMMENTED** [review]
Good work 👍

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by Its-Aman-Yadav** [comment]
Thank you @souvik-maity

**Pull request merged**
