### PR TITLE
I have uploaded the task i have been assigned
Adding header and adding some more links to the footer and improving contact section by ordering them and adding a review section #48

### PR DESCRIPTION
**Pull request by Sandhyarani23**

### CODE REVIEW

**Review by bhaavvya — CHANGES_REQUESTED** [review]
image
can you please remove the background i think without background it will look more even.

image
This review section is not looking good cause of uneven , i would suggest to increase its size a bit and also can add the curvy outline instead of the straight division.

Just change few of these things

**Review by bhaavvya — APPROVED** [review]

**Comment by Its-Aman-Yadav** [comment]
Which issue is this? @Sandhyarani23

**Comment by Sandhyarani23** [comment]
> Which issue is this? @Sandhyarani23 

Issue #48

**Review by Its-Aman-Yadav — CHANGES_REQUESTED** [review]
image
The changes you made, disturbed the content of the page, please resolve this issue

**Comment by Its-Aman-Yadav** [comment]
image
The parallex effect affecting the review page
please fix that @Sandhyarani23

**Review by Its-Aman-Yadav — COMMENTED** [review]
and raise another branch to handle merge conflicts

**Pull request closed without merging**
