### PR TITLE
input size and box color

### PR DESCRIPTION
**Pull request by puneet426**
#578 
Screenshot 2024-06-04 125153
input box is out of the original box i resolve this issue

### CODE REVIEW

**Comment by puneet426** [comment]
hello @Its-Aman-Yadav  please add level GSSoC

**Comment by Its-Aman-Yadav** [comment]
Thank you @puneet426

**Comment by puneet426** [comment]
@Its-Aman-Yadav  please close this as it is completed

**Comment by puneet426** [comment]
@Its-Aman-Yadav add level GSSoC2024

**Comment by puneet426** [comment]
please add level GSSoC 2024

**Pull request merged**
