### PR TITLE
submit  is centered in all the screens also make the nav bar visible responsively for both mobile and large screens

### PR DESCRIPTION
**Pull request by jagadeesh-debug**
centered submit button in all screens along with that solved mentioned issued of stars getting vertical also modified nav bar for mobile screen view

### CODE REVIEW

**Comment by jagadeesh-debug** [comment]
before the submit button was crossed the border in mobile view now i made it to align center in all the screens

**Review by Its-Aman-Yadav — CHANGES_REQUESTED** [review]
image
It making stars vertically

**Comment by jagadeesh-debug** [comment]
solved the issue of star

> image It making stars vertically
 

->solved the issue of stars being vertical and also modified the navbar for small screens

**Comment by Its-Aman-Yadav** [comment]
Which Issue is this?

**Comment by jagadeesh-debug** [comment]
> Which Issue is this?



> Which Issue is this?

Screenshot 2024-05-26 195511
while clicking on menu button its not showing the nav bar for mobile screens now previously it has been aligned vertically

**Comment by Its-Aman-Yadav** [comment]
I mean the issue number @jagadeesh-debug

**Comment by jagadeesh-debug** [comment]
> I mean the issue number @jagadeesh-debug 

Actually I haven't raised any issue before I directly put a pull request for you after seeing the issue in your website while inspecting but now some one mentioned the issue of nav bar #415 but I fixed before they mentioned I don't know that I need to raise an issue before contribution mine is #412 where I fixed the navbar and also the submit button  if you want mine then I will raise an issue

**Comment by Its-Aman-Yadav** [comment]
No worries @jagadeesh-debug

**Review by Its-Aman-Yadav — APPROVED** [review]

**Pull request merged**
