### PR TITLE
Changed twitter icon to Updated Version X

### PR DESCRIPTION
**Pull request by PrashantAnand03**
##PR : Description

#372  BUG: Update Twitter icon to update version X

Change made:
 
To address the bug (outdated Twitter icon), I've inserted the Font Awesome Twitter X icon code into the index.html file.

Type of PR

[X]  Bug fix

Screenshots 
Updated-X

### CODE REVIEW

**Comment by PrashantAnand03** [comment]
#372 I have fixed the bug issue, Kindly accept the Pull Request to incorporate the changes.

**Comment by Kalivarapubindusree** [comment]
plse resolve conflicts

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by PrashantAnand03** [comment]
#372 You have approved the changes kindly merged it.

**Comment by Kalivarapubindusree** [comment]
Please resolve the conflicts

**Comment by sandeepmaurya0786** [comment]
Hi! I would like to work on this issue. Can you please assign it to me?

**Comment by Its-Aman-Yadav** [comment]
Hey @sandeepmaurya0786 yeah sure, since it is open for long time without resolution you can work on it now

**Comment by sandeepmaurya0786** [comment]
ok sir i solve this issue

**Comment by sandeepmaurya0786** [comment]
thank you sir

**Pull request closed without merging**
