### PR TITLE
Added a new user experience section 

### PR DESCRIPTION
**Pull request by ananya-sh30**
#111 
I've made some changes in the website by adding 3 past-user testimonials.  I've also added hover effect on the cards to make it more appealing. 

OUTPUT: 
Screenshot 2024-05-14 124022

### CODE REVIEW

**Comment by Its-Aman-Yadav** [comment]
Hey @ananya-sh30 I like your changes but could you please place it above the get in touch section and make it horizontal rather than vertical?

**Comment by souravgope** [comment]
i can make it @Its-Aman-Yadav  pleaae assign this

**Comment by ananya-sh30** [comment]
@Its-Aman-Yadav okay I'll make the changes asap

**Comment by ananya-sh30** [comment]
@Its-Aman-Yadav I've made the changes as per the requirement. Please let me know if any other changes are to be made.

Screenshot 2024-05-15 180455

**Review by bhaavvya — COMMENTED** [review]
can you please resolve the conflict.

**Comment by Kalivarapubindusree** [comment]
Please resolve the conflicts

**Comment by ananya-sh30** [comment]
All the conflicts have been resolved now. Please review

**Pull request merged**
