### PR TITLE
done added dark theme #88

### PR DESCRIPTION
**Pull request by reshamsai150**
added the light and dark switching theme

### CODE REVIEW

**Comment by Its-Aman-Yadav** [comment]
Hey @reshamsai150 could you please place it to the upper right corner for better visibility
Thanks

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by reshamsai150** [comment]
ok

**Comment by Kalivarapubindusree** [comment]
Please resolve the conflicts @reshamsai150

**Review by Its-Aman-Yadav — CHANGES_REQUESTED** [review]
Please place it in navbar

**Comment by reshamsai150** [comment]
Ok, I will do it.

**Pull request closed without merging**
