### PR TITLE
Added "Cursor Trail Effect" to The Website

### LINKED ISSUE #932: Feat: Add a "Cursor Trail Effect" Matching to Website "Design Theme"
### Describe the feature

Hey @Its-Aman-Yadav and @Kalivarapubindusree

I would like to add a trail effect to the cursor which is sync to it and moves around while the mouse is moving.

### Add ScreenShots

**For example Like this, this is my previous work:**

https://github.com/Its-Aman-Yadav/Community-Site/assets/101971980/3b001e20-3b96-44eb-94ff-5dfb44880874

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MastanSayyad**
Hey @Its-Aman-Yadav and @Kalivarapubindusree  | Issue closes #932 

I have added the "Cursor Trail Effect" to The Website 

**Changes I made**
- Added multiple circle elements to the body.
- Styles the circles.
- The trail effect:
                    - Tracks the mouse position.
                    - Each circle follows the position of the previous circle in gradually decreasing order, 
                    - Colors are applied to the circles based on the provided array.
                    

https://github.com/Its-Aman-Yadav/Community-Site/assets/101971980/95dd3a00-a331-4cf3-ae8b-28319878190d

please take a look and review it, thank you!!

### CODE REVIEW

**Comment by Kalivarapubindusree** [comment]
please resolve conflicts

**Comment by MastanSayyad** [comment]
@Kalivarapubindusree Conflicts are resolved

**Comment by MastanSayyad** [comment]
@Kalivarapubindusree I have resolved the conflicts pls take a look

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by Its-Aman-Yadav** [comment]
please resolve conflicts

**Comment by MastanSayyad** [comment]
@Its-Aman-Yadav I have resolved the conflicts

**Comment by MastanSayyad** [comment]
@Its-Aman-Yadav @Kalivarapubindusree I have again resolved the conflicts pls merge this

**Comment by MastanSayyad** [comment]
@Its-Aman-Yadav and @Kalivarapubindusree please merge this PR to prevent more conflicts

**Comment by MastanSayyad** [comment]
@Its-Aman-Yadav Please merge this PR!!

**Pull request merged**
