### PR TITLE
Bug Fix in Rating Star

### PR DESCRIPTION
**Pull request by alpharsh**
The 4th star is out of the div

Before:
Screenshot 2024-07-03 162509

After:
Screenshot 2024-07-03 162551

closes: #937

### CODE REVIEW

**Comment by alpharsh** [comment]
@Its-Aman-Yadav please review and merge it under the gssoc

**Comment by alpharsh** [comment]
@Its-Aman-Yadav pls review

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by Its-Aman-Yadav** [comment]
please resolve conflicts

**Comment by alpharsh** [comment]
@Its-Aman-Yadav resolved now pls review

**Pull request merged**
