### PR TITLE
#issue 12 improved UI/UX

### PR DESCRIPTION
**Pull request by kairveeehh**
#12 

 as the cards were added by smo else even though the issue was assigned to me I have made some changes by giving hover effects and for the buttons in the home screen , there was a UX issue on hover the text color was white making it less visible due to yellow background , I have change it as well here are the screen shots attached 
## please review and merge my footer and this PR @Its-Aman-Yadav 
S05-13 102656
Screenshot 2024-05-13 102529
### with hover fixed ->
Screenshot 2024-05-13 102524

### CODE REVIEW

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by Its-Aman-Yadav** [comment]
Hey @kairveeehh thank you for your contribution

**Comment by kairveeehh** [comment]
> Hey @kairveeehh thank you for your contribution

welcome @Its-Aman-Yadav  and also the footer PR is also there with the changes you asked for

**Comment by Its-Aman-Yadav** [comment]
Ok, I will check that out
Thank you again

**Comment by kairveeehh** [comment]
@Its-Aman-Yadav , request to label the PR as according to the announcements in discord server of gssoc  its necessary

**Comment by kairveeehh** [comment]
@Its-Aman-Yadav please attach levels to the merged Pr

**Pull request merged**
