### PR TITLE
Create dark-theme.css

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
Adding dark theme in css
for the issue #88 adding dark theme to enhance user experience

### CODE REVIEW

**Review by Its-Aman-Yadav — CHANGES_REQUESTED** [review]
Could you please make a toggle for switching themes?

**Comment by Aditi22Bansal** [comment]
Ok

**Comment by Aditi22Bansal** [comment]
Done kindly check

**Comment by Its-Aman-Yadav** [comment]
It is not working and not properly align

**Pull request closed without merging**
