### PR TITLE
[ Feature ] Make the Form Section work #9

### PR DESCRIPTION
**Pull request by 22Yash**
Use smtpJs for Form Section .

### CODE REVIEW

**Comment by Its-Aman-Yadav** [comment]
these mails are sent to your Gmail, please change it to mine - itsamanyadav18@gmail.com

**Comment by 22Yash** [comment]
Ok I Do It 👍

**Comment by 22Yash** [comment]
I added your email id instead of me .

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by Its-Aman-Yadav** [comment]
Thank you for your contribution

**Pull request merged**
