### PR TITLE
Updates ourplan page goals section

### LINKED ISSUE #1382: Feat: Enhance our plan page Goals section
### Describe the feature

Currently the goals section of our plan page is not looking good , It is unresponsive as well as not matching with our colour scheme 

### Add ScreenShots

osvplangoal1

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Meetjain1**
## Summary

_Briefly describe the purpose of this PR._

## Description

_Explain in detail what this PR is all about. This should include the problem you're solving, the approach taken, and any technical details that reviewers need to know._

This PR styles the goals section current theme of our website . Each goal is presented in increasing order of box size for visual hierarchy. The section is responsive, with adjusted padding and font sizes for different screen sizes, and includes optional fade-in animations for enhanced user experience.

## Images

_Include any relevant images or diagrams that can help reviewers visualize the changes, if applicable_

Before 

osvplangoal1

After 

osvplangoal2

## Issue(s) Addressed

_Enter the issue number of the bug(s) that this PR fixes_

- Template should be strictly **Closes <issue_number>**
- Example: Closes #1382

## Prerequisites

- [X] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/Its-Aman-Yadav/Community-Site/blob/main/CONTRIBUITING.md)?

### CODE REVIEW

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by Its-Aman-Yadav** [comment]
Kindly resolve conflicts  @Meetjain1

**Comment by Meetjain1** [comment]
> Kindly resolve conflicts @Meetjain1

@Its-Aman-Yadav Resolved sir

**Comment by Meetjain1** [comment]
> > Kindly resolve conflicts @Meetjain1
> 
> @Its-Aman-Yadav Resolved sir

Resolved sir @Its-Aman-Yadav

**Comment by Meetjain1** [comment]
@Its-Aman-Yadav sir please review prs since the deadline is 7pm today so I request you to please review as soon as possible.  Thanks

**Comment by Meetjain1** [comment]
@Its-Aman-Yadav @Kalivarapubindusree please review before 7pm

**Comment by Meetjain1** [comment]
@Its-Aman-Yadav @Kalivarapubindusree please review before 7pm

**Comment by Meetjain1** [comment]
@Its-Aman-Yadav

**Comment by Its-Aman-Yadav** [comment]
I apologize @Meetjain1 bit busy today

**Comment by Its-Aman-Yadav** [comment]
Thank you for all of your contributions

**Pull request merged**
