### PR TITLE
updated discord btn

### PR DESCRIPTION
**Pull request by HareRamDwivedi**
Updated discord Button

Before:
Screenshot 2024-06-28 185512

After : 
Screenshot 2024-06-28 185524

### CODE REVIEW

**Comment by HareRamDwivedi** [comment]
@Its-Aman-Yadav , please assign me this under GSSoC24 and merge this PR and for any changes in this issue feel free to reach out

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by zalabhavy** [comment]
@Its-Aman-Yadav i am assigned for this issue #887 yesterday.
@HareRamDwivedi make PR without assign and you merge that !
This is not fair please remove this PR.

**Comment by zalabhavy** [comment]
@HareRamDwivedi this is not fair !
Without any efforts just make PR's and after that you ask for assign that is not correct way !
@HareRamDwivedi Learn how to contribute.

**Comment by Kalivarapubindusree** [comment]
One issue can't be assigned to two members @zalabhavy

**Comment by zalabhavy** [comment]
@Kalivarapubindusree Yes , @HareRamDwivedi is not assigned but he just make PR then asked for assign.

**Pull request merged**
