### PR TITLE
Removed unused code and extra spaces from main page code

### LINKED ISSUE #1301: Feat:remove the unused and extra spaces from the main page code
### Describe the feature

remove the extra spaces and unused code 

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
Hi i noticed that there were many code which was not been used in the main page code so i removed all of them also i have removed the extra spaces in the the main page code 

Fixes #1301

### CODE REVIEW

**Comment by aditya-bhaumik** [comment]
@Its-Aman-Yadav please review and merge this pull request

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by Its-Aman-Yadav** [comment]
Kindly resolve conflicts

**Comment by aditya-bhaumik** [comment]
Resolved conflicts @Its-Aman-Yadav

**Comment by aditya-bhaumik** [comment]
@Its-Aman-Yadav please provide the gssoc labels

**Comment by aditya-bhaumik** [comment]
@Its-Aman-Yadav please add the gssoc and the level 1 label

**Comment by aditya-bhaumik** [comment]
@Kalivarapubindusree please provide the gssoc labels and assign this pr

**Pull request merged**
