### PR TITLE
#Updated the Mountains image in the hero section #7

### PR DESCRIPTION
**Pull request by Sudhish23**

### CODE REVIEW

**Comment by Its-Aman-Yadav** [comment]
Hey @Sudhish23 you added some low quality images please add 4k images to it and it is difficult to read cause of bright images.
So, my suggestion is to add 4k and some dark images

**Comment by Sudhish23** [comment]
Okay 👍

**Comment by Sudhish23** [comment]
Okay 
Hey, you assigned this issue to someone else can I still work on this issue.

**Comment by Sudhish23** [comment]
Please suggest any changes that can make my work better.

**Comment by Its-Aman-Yadav** [comment]
Hey @Sudhish23 yes you can

**Comment by Sudhish23** [comment]
Okay Thankyou 
I added new images is it good.

**Comment by Its-Aman-Yadav** [comment]
yeah that's looks good

**Review by Its-Aman-Yadav — APPROVED** [review]
Nicely done

**Pull request merged**
