### PR TITLE
issue #11

### PR DESCRIPTION
**Pull request by kairveeehh**
@Its-Aman-Yadav I have removed all the empty links also somehow my footer is already shown in the site and it is the exact same code , did you merge it already??
## please review and merge this and let me know about the previous one 
@Its-Aman-Yadav

### CODE REVIEW

**Comment by Its-Aman-Yadav** [comment]
Hey @kairveeehh, I have checked your code but It is conflicting with the other code, IDK what will be reason but you can preview your edits here https://deploy-preview-178--opensourcevillage.netlify.app/

Try to fix it

**Review by Its-Aman-Yadav — CHANGES_REQUESTED** [review]
maybe due to some class name conflicts with other class names

**Comment by kairveeehh** [comment]
@Its-Aman-Yadav but my code is already incorporated in the site as I told you ki due to my two PR both changes are done in the one only , I  just have removed the extra links in this

**Comment by Its-Aman-Yadav** [comment]
Hey @bhaavvya can you look this issue?

**Comment by Its-Aman-Yadav** [comment]
@kairveeehh don't worry you will get what you deserve

**Comment by kairveeehh** [comment]
@Its-Aman-Yadav I have tried to fix it here as well as created new branch and opened up a new PR  also 
## please review and merge any of these when available 
if you go on to merge the other PR , please assign and add the labels 
thankyou :)

**Pull request closed without merging**
