### PR TITLE
Multiple changes (footer and navbar)

### PR DESCRIPTION
**Pull request by Hemav009**
1. The footer of all pages changed (over flow fixed).
2. Nav bar logo title of index and privacy policy page changed.
**Before**
Screenshot 2024-07-02 202313
**After**
image

Before
Screenshot 2024-07-02 202344

After
Screenshot 2024-07-02 204326

### CODE REVIEW

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by Its-Aman-Yadav** [comment]
remove conflicts @Hemav009

**Comment by Hemav009** [comment]
@Its-Aman-Yadav  resolved

**Comment by Its-Aman-Yadav** [comment]
Still have conflicts

**Comment by Hemav009** [comment]
@Its-Aman-Yadav  can you merge it now?please merge this pr first

**Comment by Its-Aman-Yadav** [comment]
It is still making conflicts

**Comment by Hemav009** [comment]
@Its-Aman-Yadav  You can merge it now i suppose?

**Pull request merged**
