### PR TITLE
dark mode in network page

### PR DESCRIPTION
**Pull request by ANKeshri**
fixes : #1087

Add dark mode feature in network page . 

before : 

https://github.com/user-attachments/assets/737992ef-429a-4175-abf9-4f3c334b085d

after :  

https://github.com/user-attachments/assets/aa5b221b-01f1-4340-b54a-d8162657dd21

### CODE REVIEW

**Comment by ANKeshri** [comment]
@Its-Aman-Yadav please review and merge my pr

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by Its-Aman-Yadav** [comment]
Kindly resolve conflicts @ANKeshri

**Comment by ANKeshri** [comment]
@Its-Aman-Yadav done please merge it

**Comment by Its-Aman-Yadav** [comment]
Thank you

**Pull request merged**
