### PR TITLE
changed the border in contact form

### PR DESCRIPTION
**Pull request by SadafKausar2025**

### CODE REVIEW

**Comment by Its-Aman-Yadav** [comment]
hey @SadafKausar2025 that's looks cool, could you please make it by default instead of hover effect?

**Comment by SadafKausar2025** [comment]
ya sure

**Comment by Its-Aman-Yadav** [comment]
Thank you for your contribution

**Comment by SadafKausar2025** [comment]
hello @Its-Aman-Yadav 
this PR is not counted in my contribution . can you 
please give me level in this PR , so that it will be added in my contribution

**Pull request merged**
