### PR TITLE
Updated navbar

### PR DESCRIPTION
**Pull request by Nayanika1402**
Fixes Issue #235 
The navbar is updated...
Screenshot:
Screenshot 2024-05-16 104817

### CODE REVIEW

**Comment by Nayanika1402** [comment]
@Its-Aman-Yadav I want to mention one thing about the labelling system.You have tagged most of the issues with Level 1, level 2,level 3 tags but as mentioned by Sanjay sir who is gssoc program manager the labelling should be Level1,Level2,Level3. There should be no gap between the level and the number or else the PR's will not be counted.I will appreciate if you kindly look into this matter.

**Comment by Its-Aman-Yadav** [comment]
Hey @Nayanika1402 that looks nice but the font is more bold and didn't suit the theme of the page, could you please add new font style like something smooth to match?

Yeah, sure I have updated all the labels name, thank you for your kind information, much appreciated

**Comment by Its-Aman-Yadav** [comment]
Also please remove all the conflicts before merging

**Comment by Nayanika1402** [comment]
Screenshot:
Screenshot 2024-05-16 194844
See if you like this font @Its-Aman-Yadav or else you can suggest the font from the fontgoogleapis I will apply that.

**Comment by Nayanika1402** [comment]
@Its-Aman-Yadav I have changed the navbar with the addition of icon in review and the font size is changed.
Screenshot:
Screenshot 2024-05-16 202550

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by Its-Aman-Yadav** [comment]
Thank you @Nayanika1402 once again for your wonderful work
Much appreciated

**Pull request merged**
