### PR TITLE
Fixed the UI and UX of the Navbar

### PR DESCRIPTION
**Pull request by Sheryar-bit**
I have successfully fixed the UI and UX of the Navbar and I have added some extra effect into it.  
#265 

image

### CODE REVIEW

**Review by bhaavvya — COMMENTED** [review]
hello @Sheryar-bit can you please remove this shadow cause on hovering at Home imprint of all the items on navbar appears which doesn't look good.
image

**Review by bhaavvya — CHANGES_REQUESTED** [review]
Please do the required changes

**Comment by Sheryar-bit** [comment]
> hello @Sheryar-bit can you please remove this shadow cause on hovering at Home imprint of all the items on navbar appears which doesn't look good.And also this hover efferct is comming in the shadow part and not at the actual place.
> 
> image

Sure I will work, Thank you for the suggestion l.

**Comment by Sheryar-bit** [comment]
> hello @Sheryar-bit can you please remove this shadow cause on hovering at Home imprint of all the items on navbar appears which doesn't look good.And also this hover efferct is comming in the shadow part and not at the actual place.
> 
> image

@bhaavvya, I have fixed the issue that you suggested you can check the pr
image

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by Its-Aman-Yadav** [comment]
Thank you @Sheryar-bit

**Pull request merged**
