### PR TITLE
change Discord ,Linkedin styling and front page appearance

### PR DESCRIPTION
**Pull request by kashisharora9462**
Fixed Issue #269 

## Changes Proposed:-

@Its-Aman-Yadav @Kalivarapubindusree 
I have enhanced the styling of the links (LinkedIn and Discord) to make them more visually appealing. Initially, only the names of the links are displayed to the user. When the user hovers over a link, the name of the link (e.g., LinkedIn) along with its logo is shown, and the background colour changes. I have also added a smooth transition effect to ensure these changes occur seamlessly. Additionally, I have updated the font family of the headings and adjusted the colour theme to harmonize with the background.

I have tried my best to improve the overall design. If you have any further changes or suggestions, please let me know. I kindly request you to merge these updates into the repository to enhance its visual appeal.

My code follow the code style of this project.

Screenshot:-

Screenshot 2024-05-18 092611

on hover:-
Screenshot 2024-05-18 092834

### CODE REVIEW

**Comment by Kalivarapubindusree** [comment]
please resolve conflicts

**Comment by kashisharora9462** [comment]
Resolved .Please check and let me k.now if some other changes need to be done.I will be happy to do improvements needed

**Comment by kashisharora9462** [comment]
Conflicts resolved. Please let me know if now you are able to merge or not.

**Comment by kashisharora9462** [comment]
Thankyou. It's my first contribution under GSsoc'24. Happy to work.

**Comment by Kalivarapubindusree** [comment]
All the very best @kashisharora9462 ur work was great and I hope u contribute more n more to this project.

**Comment by kashisharora9462** [comment]
Thank you and I will.

**Comment by sanjay-kv** [comment]
I fixed the gamesphere issue , community site I don't have access. i will request PA

**Comment by kashisharora9462** [comment]
Ok, thanks. Please contact with project admin or mentor of community site
and solve it as soon as possible.

**Pull request merged**
