### PR TITLE
Created a responsive navbar and embedded website's logo in it.

### PR DESCRIPTION
**Pull request by sonarani1**
Fixed the issue no. #68 

Changed:
Created a responsive navbar on the website and added the website logo to the navbar.

lines of code are original and not plagiarized.

Screenshot (44)
Screenshot (43)

### CODE REVIEW

**Comment by sonarani1** [comment]
Kindly accept this PR @Its-Aman-Yadav

**Comment by sonarani1** [comment]
Hey @Its-Aman-Yadav  kindly merge this PR.

**Comment by Its-Aman-Yadav** [comment]
Hey @sonarani1 that's looks good but could you please change the logo design? its looking odd

**Comment by sonarani1** [comment]
Can you clarify more about how you want your logo? Do you want a new logo design in the navbar or Should I change the shape from round to rectangle? Please provide me with your LinkedIn ID so that I can know your confirmation. @Its-Aman-Yadav

**Comment by Its-Aman-Yadav** [comment]
The logo is quite big and touching the border of the navbar please make it fit inside rather than touching borders

**Comment by sonarani1** [comment]
Okay. raising a new PR in few minutes.
@Its-Aman-Yadav

**Pull request closed without merging**
