### PR TITLE
 Multiple issues fixed : Testimonial buttons working, Duplicate sections removed; CSS of About Us, Contact, Member, Our plan and Our program (5 webpages) fixed

### PR DESCRIPTION
**Pull request by debangi29**
# Fixed issues #551 and #568
# 1. Make Testimonial button clickable
### New:

https://github.com/Its-Aman-Yadav/Community-Site/assets/117537653/70fd8790-5913-410a-9114-c0c51dae75d4

### Old:
image

# 2. Extra testimonial section Removed Now
### New
image
### Old
image

# 3. Add better CSS to Our Plan web Page 
### New
image

### Old
Screenshot (329)

# 4. Add better CSS to Our Program web page
### Hovering effects added:
image

image

# 5. Add better CSS to Become a member web page
### NEW
image
image

### Old

image
image

# 6. Enhance the footer
### Added links to the footer
image

**Old:**
image

### CODE REVIEW

**Comment by debangi29** [comment]
Please review and merge this PR @Its-Aman-Yadav 
Thank you 🙂

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by Its-Aman-Yadav** [comment]
Please remove the merge conflicts, Thank you @debangi29

**Comment by debangi29** [comment]
I am unable to make commits to this PR because of the conflicts @Its-Aman-Yadav 
I am making a new PR making the same Changes
Thank You :)

**Comment by Its-Aman-Yadav** [comment]
Ok sure

**Pull request closed without merging**
