### PR TITLE
Fixed the Bug #477

### PR DESCRIPTION
**Pull request by Harsha19-08**
Fixed the issue #477 
Description:

This pull request addresses the following issues:

1. Issue #477: Navbar alignment
   - Fixed the alignment of the navbar elements to ensure proper spacing and positioning.

2. Footer alignment
   - Corrected the alignment of the footer content, ensuring it is properly centered or justified as per the design requirements.

3. Subscriber option
   - Implemented the subscriber option functionality, allowing users to subscribe to the application or service.

By resolving these issues, the user experience has been improved, and the overall design and functionality of the application have been enhanced.

Changes:
- Modified the CSS styles for the navbar to fix the alignment issues.
- Updated the HTML and CSS for the footer to correct the alignment.
- Added the necessary HTML, CSS, and JavaScript (if applicable) to implement the subscriber option.

Testing:
- Thoroughly tested the changes locally to ensure the navbar, footer, and subscriber option are working as expected.
- Verified the responsiveness of the changes across different screen sizes and devices.

Note: Please review the changes carefully and provide any feedback or suggestions. If you have any questions or need further clarification, feel free to ask.

### CODE REVIEW

**Comment by Its-Aman-Yadav** [comment]
Please remove the conflicts

**Comment by Harsha19-08** [comment]
@Its-Aman-Yadav  resolved the conflicts

**Comment by Its-Aman-Yadav** [comment]
This issue is not raised by you 
Thank you

**Comment by Harsha19-08** [comment]
Please know about the basic contributions are done individually it's about solving the issues not the person who raise the issues will always be solving and assigned.. So first know the style of contributing

**Pull request closed without merging**
