### PR TITLE
Updated images to slideshow #128

### PR DESCRIPTION
**Pull request by DevNandini02**
I have removed the previous images and added darker images to the slideshow. #128 

After changes
[Open Source Village.webm](https://github.com/Its-Aman-Yadav/Community-Site/assets/124669890/dfa0833a-ffce-4cd9-88fe-a2373acfad8f)
Please open the link.

### CODE REVIEW

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by Its-Aman-Yadav** [comment]
Thank you @DevNandini02 just remove the conflicts before merging

**Comment by DevNandini02** [comment]
> Thank you @DevNandini02 just remove the conflicts before merging

@Its-Aman-Yadav sir i am not able to resolve the conflicts in the same branch. Can i make another branch and then send the pull request again?

**Comment by Its-Aman-Yadav** [comment]
yeah sure

**Comment by DevNandini02** [comment]
@Its-Aman-Yadav sir since there is no conflicts now, so do i have to merge the updates to the main branch or you'll do it?

**Review by Its-Aman-Yadav — APPROVED** [review]

**Review by bhaavvya — APPROVED** [review]

**Review by Its-Aman-Yadav — APPROVED** [review]

**Comment by Its-Aman-Yadav** [comment]
Thank you @DevNandini02

**Pull request merged**
